.\" rejmerge.conf(5) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd December 27, 2023
.Dt REJMERGE.CONF 5
.Os
.\" ==================================================================
.Sh NAME
.Nm rejmerge.conf
.Nd configuration file for rejmerge
.\" ==================================================================
.Sh SYNOPSIS
.Nm /etc/rejmerge.conf
.\" ==================================================================
.Sh DESCRIPTION
This manual page describes the format of the
.Pa rejmerge.conf
file.
This file can be used to alter the way
.Xr rejmerge 8
displays file differences and performs file merges.
Changing the default behavior is done by re-defining the shell
functions
.Em rejmerge_diff ,
.Em rejmerge_merge
and shell variables
.Em EDITOR ,
.Em PAGER .
.\" ------------------------------------------------------------------
.Ss rejmerge_diff
This function is executed once for each rejected file.
Arguments
.Em $1
and
.Em $2
contains the path to a temporary file where this function should write
its result.
The contents of the temporary file will later be presented to the user
as the difference between the two files.
.\" ------------------------------------------------------------------
.Ss rejmerge_merge
This function is executed when the user chooses to merge two files.
Argument
.Em $1
and
.Em $2
contains the paths to the installed and rejected files.
Argument
.Em $3
contains the path to a temporary file where this function should write
its result.
The contents of the temporary file will later be presented to the user
as the merge result.
.Pp
This function also has the option to set the variable
.Em REJMERGE_MERGE_INFO .
The contents of this variable will be displayed as informational text
after a merge has been performed.
Its purpose is to provide information about the merge
.Pq e.g. Dq 5 merge conflicts found .
.\" ------------------------------------------------------------------
.Ss EDITOR
This variable defines the editor used in
.Sy rejmerge_merge
operation instead of the default
.Ev EDITOR
environment variable.
.\" ------------------------------------------------------------------
.Ss PAGER
This variable defines the pager used in
.Sy rejmerge_diff
and
.Sy rejmerge_merge
operations instead of the default
.Ev PAGER
environment variable.
.\" ==================================================================
.Sh FILES
.Bl -tag -width "/etc/rejmerge.conf" -compact
.It Pa /etc/rejmerge.conf
Default location for the file described in this manual page.
.El
.\" ==================================================================
.Sh EXAMPLES
If you want to produce side-by-side output for diffs, add the
following line to your configuration file:
.Bd -literal -offset indent
rejmerge_diff() { diff -y $1 $2 > $3 ; }
.Ed
.Pp
If you want to produce unified and colorized output:
.Bd -literal -offset indent
rejmerge_diff() { diff -u --color=always $1 $2 > $3 ; }
.Ed
.Pp
If you want to use
.Xr sdiff 1
to merge files instead of the default
.Xr diff 1 :
.Bd -literal -offset indent
rejmerge_merge() { sdiff -o $3 $1 $2 ; }
.Ed
.\" ==================================================================
.Sh SEE ALSO
.Xr rejmerge 8
.\" vim: cc=72 tw=70
.\" End of file.
