.\" rejmerge(8) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd June 19, 2024
.Dt REJMERGE 8
.Os
.\" ==================================================================
.Sh NAME
.Nm rejmerge
.Nd merge files that were rejected during package upgrades
.\" ==================================================================
.Sh SYNOPSIS
.Nm rejmerge
.Op Fl hnv
.Op Fl c Ar conffile
.Op Fl r Ar rootdir
.\" ==================================================================
.Sh DESCRIPTION
.Nm
is a package management utility, which merges files that were rejected
during package upgrades.
.Pp
For each rejected file found in
.Pa /var/lib/pkg/rejected/ ,
.Nm
will display difference between installed version and the rejected
version.
The user can the choose to keep the installed version, upgrade to the
rejected or perform a merge of the two.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar conffile , Fl -config Ns = Ns Ar conffile
Specify an alternate configuration file instead of the default
.Pa /etc/rejmerge.conf .
.It Fl n , Fl -dry-run
Print the differences between an installed version and rejected one, but
do not execute any actions.
.It Fl r Ar rootdir , Fl -root Ns = Ns Ar rootdir
Specify an alternate root directory instead of the default
.Ql / .
This should be used if you want to merge rejected files on a temporary
mounted partition, which is
.Dq owned
by another system.
.It Fl v , Fl -version
Print version and exit.
.It Fl h , Fl -help
Print help and exit.
.El
.\" ==================================================================
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm :
.Bl -tag -width Ds
.It Ev EDITOR
The editor to use instead of
.Xr vi 1 .
.It Ev PAGER
The pager to use instead of
.Xr more 1 .
.It Ev TMPDIR
Directory in which to place temporary files.
If unset or set but unavailable,
.Pa /tmp
is used.
.El
.Pp
.Sy Important :
All the above variables may be overridden in
.Pa /etc/rejmerge.conf .
.\" ==================================================================
.Sh FILES
.Bl -tag -width "/var/lib/pkg/rejected/" -compact
.It Pa /etc/rejmerge.conf
Configuration file.
.It Pa /var/lib/pkg/rejected/
Directory where rejected files are stored.
.El
.\" ==================================================================
.Sh SEE ALSO
.Xr rejmerge.conf 5
.\" ==================================================================
.Sh AUTHORS
Originally written by
.An Per Lidén Aq Mt per@fukt.bth.se
as part of
.Dq Sy pkgutils
package for
.Lk http://crux.nu "CRUX" .
.Pp
This implementation was extensively re-worked for Zeppe-Lin System by
.An Alexandr Savca Aq Mt alexandr.savca89@gmail.com .
.\" ==================================================================
.Sh CAVEATS
While only root can merge system files, the
.Sy -n Ns / Ns Sy --dry-run
option allows running
.Nm
as a regular user to view the differences between installed and
rejected files without making any changes.
.Pp
Note that you may encounter the situation when the rejected file has
very strict permissions (e.g. 0400) that prohibit regular users from
reading its content.
For example:
.Bd -literal -offset indent
$ PAGER=cat rejmerge -n
diff: /var/lib/pkg/rejected/etc/tor/torrc: Permission denied
=======> /etc/tor/torrc
=======> [K]eep [U]pgrade [M]erge [D]iff [S]kip?
.Ed
.Pp
Just run
.Nm
as root if you still want to view the diff.
.\" vim: cc=72 tw=70
.\" End of file.
