.\" rejmerge(8) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 3, 2023
.Dt REJMERGE 8
.Os rejmerge @VERSION@
.Sh NAME
.Nm rejmerge
.Nd merge files that were rejected during package upgrades
.Sh SYNOPSIS
.Nm rejmerge
.Op Fl c Ar conffile
.Op Fl n
.Op Fl r Ar rootdir
.Nm
.Op Fl h
.Nm
.Op Fl v
.Sh DESCRIPTION
.Nm
is a package management utility that helps you merge files that were
rejected during package upgrades.
.Pp
For each rejected file found in
.Pa /var/lib/pkg/rejected/ ,
.Nm
will display difference between installed version and the rejected
version.
The user can the choose to keep the installed version, upgrade to the
rejected or perform a merge of the two.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar conffile , Fl -config Ns = Ns Ar conffile
Specify an alternate configuration file instead of the default
.Pa /etc/rejmerge.conf .
.It Fl n , Fl -dry-run
Print the differences between an installed version and rejected one, but
do not execute any actions.
.It Fl r Ar rootdir , Fl -root Ns = Ns Ar rootdir
Specify an alternate root directory instead of the default
.Ql / .
This should be used if you want to merge rejected files on a temporary
mounted partition, which is "owned" by another system.
.It Fl v , Fl -version
Print version and exit.
.It Fl h , Fl -help
Print help and exit.
.El
.Sh ENVIRONMENT
If the following environment variable exists it will be utilized by
.Nm
(unless
.Pa /etc/rejmerge.conf
overrides them):
.Bl -tag -width Ds
.It Ev EDITOR
.Pa /bin/vi
if unset.
.It Ev PAGER
.Pa /bin/more
if unset.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/rejmerge.conf
Configuration file.
.It Pa /var/lib/pkg/rejected/
Directory where rejected files are stored.
.El
.Sh SEE ALSO
.Xr rejmerge.conf 5
.Sh AUTHORS
The original implementation of
.Nm
was done by
.An Per Lidén Aq Mt per@fukt.bth.se ,
the author of
.Lk http://crux.nu CRUX ,
as part of
.Dq pkgutils
package, and was maintained for years (and still maintaining) by CRUX
team.
.Pp
This implementation was extensively re-worked for
.Lk http://zeppel.ink Zeppe-Lin
by
.An Alexandr Savca Aq Mt alexandr.savca89@gmail.com .
.Sh CAVEATS
While only root can merge system files, the
.Sy -n Ns / Ns Sy --dry-run
option allows running
.Nm
as a regular user to view the differences between installed and
rejected files without making any changes.
.Pp
Note that you may encounter the situation when the rejected file has
very strict permissions (e.g., 0400) that prohibit regular users from
reading its content.
For example:
.Bd -literal -offset indent
$ PAGER=cat rejmerge -n
diff: /var/lib/pkg/rejected/etc/tor/torrc: Permission denied
=======> /etc/tor/torrc
=======> [K]eep [U]pgrade [M]erge [D]iff [S]kip?
.Ed
.Pp
Just run
.Nm
as root if you still want to view the diff.
.\" vim: cc=72 tw=70
.\" End of file.
